name: Deploy FastAPI to Railway

on:
  push:
    branches: [ api ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and run tests
      run: |
        pip install -r requirements.txt
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/test_predict.py

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t mohameddmohy/mlops-final-project-api:latest .
        docker push mohameddmohy/mlops-final-project-api:latest